### ISSUE TITLE
neoclassicism folder missing

### ISSUE THREAD

**Issue by delfimpandiani** [asahi417/wikiart-crawler#1]
Hi! For some reason the neoclassicism folder of images is not not found, so not downloadable. All the other art_styles are working fine.

**Comment by asahi417** [comment]
Hi thanks for pointing out the issue! I have no clue why the link to the neoclassicism was removed, but I might deleted it by accident when I uploaded some new files... I have re-uploaded it so now you should be able to use it.

https://github.com/asahi417/wikiart-image-dataset/releases/download/v0.0.0/neoclassicism.zip

**Comment by delfimpandiani** [comment]
Thank you very much!
