### ISSUE TITLE
Filter by Tag

### ISSUE THREAD

**Issue by manigalati** [asahi417/wikiart-crawler#4]
Dear authors,

First of all, thank you for sharing your work. I'd like to use your tool to download images from WikiArt, and I have noticed it is possible to filter by tag on their website: https://www.wikiart.org/en/paintingadvancedsearch

Is it possible to filter in a similar way the dataset by tag also using your tool?

Thank you in advance,
Francesco

**Comment by asahi417** [comment]
You can filter the result by tags like style with the library. See the following section in the readme.

https://github.com/asahi417/wikiart-image-dataset?tab=readme-ov-file#wikiart-crawler
